import {extname} from 'path';
const specialFiles:Record<string,string> = {
  '.bashrc': 'bash',
  '.bash_profile': 'bash',
  '.bash_logout': 'bash',
  '.zshrc': 'shell',
  '.zshenv': 'shell',
  '.zprofile': 'shell',
  '.babelrc': 'json',
  '.eslintrc': 'json',
  '.gitignore': 'plaintext',
  '.gitattributes': 'plaintext',
  '.gitconfig': 'ini',
  '.npmrc': 'ini',
  '.dockerignore': 'plaintext',
  '.editorconfig': 'ini',
  'Makefile': 'makefile',
  'Dockerfile': 'dockerfile',
  'CMakeLists.txt': 'cmake'
};
const extensionToFormat:Record<string,string> = {
  '1c': '1c',
  'abnf': 'abnf',
  'log': 'accesslog',
  'as': 'actionscript',
  'ada': 'ada',
  'angelscript': 'angelscript',
  'apache': 'apache',
  'applescript': 'applescript',
  'arcade': 'arcade',
  'ino': 'arduino',
  'arm': 'armasm',
  'xml': 'xml',
  'adoc': 'asciidoc',
  'aj': 'aspectj',
  'ahk': 'autohotkey',
  'au3': 'autoit',
  //'asm': 'avrasm',
  'awk': 'awk',
  'dax': 'axapta',
  'sh': 'bash',
  'bas': 'basic',
  'bnf': 'bnf',
  'b': 'brainfuck',
  'c': 'c',
  'cal': 'cal',
  'capnp': 'capnproto',
  'ceylon': 'ceylon',
  'icl': 'clean',
  'clj': 'clojure',
  'cljrepl': 'clojure-repl',
  'cmake': 'cmake',
  'coffee': 'coffeescript',
  'coq': 'coq',
  'cos': 'cos',
  'cpp': 'cpp',
  'h':'c',
  'hpp':'cpp',
  'crmsh': 'crmsh',
  'cr': 'crystal',
  'cs': 'csharp',
  'csp': 'csp',
  'css': 'css',
  'd': 'd',
  'md': 'markdown',
  'dart': 'dart',
  'pas': 'delphi',
  'diff': 'diff',
  'django': 'django',
  'zone': 'dns',
  'dockerfile': 'dockerfile',
  'bat': 'dos',
  'dsconfig': 'dsconfig',
  'dts': 'dts',
  'dust': 'dust',
  'ebnf': 'ebnf',
  'ex': 'elixir',
  'elm': 'elm',
  'rb': 'ruby',
  'erb': 'erb',
  'erl': 'erlang',
  'xrl': 'erlang-repl',
  'xls': 'excel',
  'fix': 'fix',
  'flix': 'flix',
  'f': 'fortran',
  'fs': 'fsharp',
  'gms': 'gams',
  'gss': 'gauss',
  'gcode': 'gcode',
  'feature': 'gherkin',
  'glsl': 'glsl',
  'gml': 'gml',
  'go': 'go',
  'golo': 'golo',
  'gradle': 'gradle',
  'graphql': 'graphql',
  'groovy': 'groovy',
  'haml': 'haml',
  'hbs': 'handlebars',
  'hs': 'haskell',
  'hx': 'haxe',
  'hsp': 'hsp',
  'http': 'http',
  'hy': 'hy',
  'ni': 'inform7',
  'ini': 'ini',
  'irpf90': 'irpf90',
  'isbl': 'isbl',
  'java': 'java',
  'js': 'javascript',
  'jboss-cli': 'jboss-cli',
  'json': 'json',
  'jl': 'julia',
  'juliatpl': 'julia-repl',
  'kt': 'kotlin',
  'lasso': 'lasso',
  'tex': 'latex',
  'ldif': 'ldif',
  'leaf': 'leaf',
  'less': 'less',
  'lisp': 'lisp',
  'livecodeserver': 'livecodeserver',
  'ls': 'livescript',
  'll': 'llvm',
  'lsl': 'lsl',
  'lua': 'lua',
  'mak': 'makefile',
  'm': 'mathematica',
  'mat': 'matlab',
  'max': 'maxima',
  'mel': 'mel',
  //'m': 'mercury',
  'mips': 'mipsasm',
  'miz': 'mizar',
  'pl': 'perl',
  'ep': 'mojolicious',
  'monkey': 'monkey',
  'moon': 'moonscript',
  'n1ql': 'n1ql',
  'nt': 'nestedtext',
  'nginx': 'nginx',
  'nim': 'nim',
  'nix': 'nix',
  'node': 'node-repl',
  'nsi': 'nsis',
  //'m': 'objectivec',
  'ml': 'ocaml',
  'scad': 'openscad',
  'oxygene': 'oxygene',
  'parser3': 'parser3',
  'pf': 'pf',
  'pgsql': 'pgsql',
  'php': 'php',
  'phtml': 'php-template',
  'txt': 'plaintext',
  'pony': 'pony',
  'ps1': 'powershell',
  'pde': 'processing',
  'profile': 'profile',
  //'pl': 'prolog',
  'properties': 'properties',
  'proto': 'protobuf',
  'pp': 'puppet',
  'pb': 'purebasic',
  'py': 'python',
  'pycon': 'python-repl',
  'q': 'q',
  'qml': 'qml',
  'r': 'r',
  're': 'reasonml',
  'rib': 'rib',
  'graph': 'roboconf',
  'routeros': 'routeros',
  'rsl': 'rsl',
  'rules': 'ruleslanguage',
  'rs': 'rust',
  'sas': 'sas',
  'scala': 'scala',
  'scm': 'scheme',
  'sce': 'scilab',
  'scss': 'scss',
  //'sh': 'shell',
  'smali': 'smali',
  'st': 'smalltalk',
  'sml': 'sml',
  'sqf': 'sqf',
  'sql': 'sql',
  'stan': 'stan',
  'do': 'stata',
  'stp': 'step21',
  'styl': 'stylus',
  'subunit': 'subunit',
  'swift': 'swift',
  'taggerscript': 'taggerscript',
  'yaml': 'yaml',
  'tap': 'tap',
  'tcl': 'tcl',
  'thrift': 'thrift',
  'tp': 'tp',
  'twig': 'twig',
  'ts': 'typescript',
  'vala': 'vala',
  'vb': 'vbnet',
  'vbs': 'vbscript',
  'html': 'html',
  'v': 'verilog',
  'vhdl': 'vhdl',
  'vim': 'vim',
  'wat': 'wasm',
  'wren': 'wren',
  'asm': 'x86asm',
  'xl': 'xl',
  'xq': 'xquery',
  'zep': 'zephir',
};
const image_ext=['jpg','gif','svg','png','ico']
const video_ext=['mp4','avi','mkv']
export function guessFileFormat(fileName:string) {
  const lowerFileName = fileName.toLowerCase();
  const exists=specialFiles[lowerFileName]
  if (exists)
    return exists
  const extension = lowerFileName.split('.').slice(-1)[0]
  if (extension==null)
    return
  if (image_ext.includes(extension))
    return 'image'  
  if (video_ext.includes(extension))
    return 'video'  
  return extensionToFormat[extension]
}
const mimeTypes: Record<string, string> = {
    // Images
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.png': 'image/png',
    '.gif': 'image/gif',
    '.webp': 'image/webp',
    '.tiff': 'image/tiff',
    '.tif': 'image/tiff',
    '.svg': 'image/svg+xml',
    '.ico': 'image/x-icon',
    '.bmp': 'image/bmp',
    '.avif': 'image/avif',
    
    // Audio
    '.mp3': 'audio/mpeg',
    '.wav': 'audio/wav',
    '.ogg': 'audio/ogg',
    '.m4a': 'audio/mp4',
    '.aac': 'audio/aac',
    '.weba': 'audio/webm',
    '.mid': 'audio/midi',
    '.midi': 'audio/midi',
    
    // Video
    '.mp4': 'video/mp4',
    '.webm': 'video/webm',
    '.avi': 'video/x-msvideo',
    '.mpeg': 'video/mpeg',
    '.mov': 'video/quicktime',
    '.wmv': 'video/x-ms-wmv',
    '.flv': 'video/x-flv',
    '.mkv': 'video/x-matroska',
    
    // Documents
    '.pdf': 'application/pdf',
    '.doc': 'application/msword',
    '.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    '.xls': 'application/vnd.ms-excel',
    '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    '.ppt': 'application/vnd.ms-powerpoint',
    '.pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    '.odt': 'application/vnd.oasis.opendocument.text',
    '.ods': 'application/vnd.oasis.opendocument.spreadsheet',
    '.odp': 'application/vnd.oasis.opendocument.presentation',
    
    // Web
    '.html': 'text/html',
    '.htm': 'text/html',
    '.css': 'text/css',
    '.js': 'text/javascript',
    '.json': 'application/json',
    '.xml': 'application/xml',
    '.txt': 'text/plain',
    '.csv': 'text/csv',
    '.md': 'text/markdown',
    
    // Archives
    '.zip': 'application/zip',
    '.rar': 'application/x-rar-compressed',
    '.7z': 'application/x-7z-compressed',
    '.tar': 'application/x-tar',
    '.gz': 'application/gzip',
    
    // Fonts
    '.ttf': 'font/ttf',
    '.otf': 'font/otf',
    '.woff': 'font/woff',
    '.woff2': 'font/woff2',
    '.eot': 'application/vnd.ms-fontobject',
    
    // Other
    '.swf': 'application/x-shockwave-flash',
    '.exe': 'application/x-msdownload',
    '.dll': 'application/x-msdownload',
    '.bin': 'application/octet-stream',
    '.iso': 'application/x-iso9660-image',
    '.apk': 'application/vnd.android.package-archive',
    '.rtf': 'application/rtf',
    
    // Email
    '.eml': 'message/rfc822',
    
    // 3D Models
    '.obj': 'model/obj',
    '.stl': 'model/stl',
    '.gltf': 'model/gltf+json',
    '.glb': 'model/gltf-binary',
    
    // Calendar
    '.ics': 'text/calendar',
    
    // Scientific/Technical
    '.tex': 'application/x-tex',
    '.latex': 'application/x-latex',
    '.mathml': 'application/mathml+xml',
    
    // Database
    '.db': 'application/x-sqlite3',
    '.sql': 'application/sql',
    
    // Configuration
    '.ini': 'text/plain',
    '.cfg': 'text/plain',
    '.conf': 'text/plain',
    '.yml': 'text/yaml',
    '.yaml': 'text/yaml',
    '.toml': 'application/toml',
    
    // Vector Graphics
    '.ai': 'application/postscript',
    '.eps': 'application/postscript',
    '.ps': 'application/postscript'
  };
export function guessMimeType(fileName:string) {
  const ext = extname(fileName).toLowerCase();
  return mimeTypes[ext] || 'application/octet-stream';
}

